openapi: 3.1.0
info:
  title: eth_getBlockByNumber
  description: Retrieves information from a particular block in the blockchain.
  version: '1.0'
servers:
  - url: 'https://bsc-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: eth-getBlockByNumber
        summary: eth_getBlockByNumber
        description: Returns information about a block by block number.
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: 64a9df0874fb4a93b9d0a3849de012d3
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_getBlockByNumber
        x-readme:
          explorer-enabled: false
          samples-languages:
            - javascript
            - curl
            - python
            - go
        responses:
          '200':
            description: 'Returns a block object with the following fields, or null when no block was found.'
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_block
