openapi: 3.1.0
info:
  title: eth_getFilterLogs
  version: '1.0'
servers:
  - url: 'https://bsc-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getFilterLogs
        description: Returns an array of all logs matching filter with given id. Can compute the same results with an eth_getLogs call.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: 64a9df0874fb4a93b9d0a3849de012d3
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_getFilterLogs
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_getLogs
        operationId: eth-getFilterLogs
