openapi: 3.1.0
info:
  title: eth_getUncleByBlockHashAndIndex
  version: '1.0'
servers:
  - url: 'https://bsc-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getUncleByBlockHashAndIndex
        description: Returns information about an uncle of a block by hash and uncle index position.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: 64a9df0874fb4a93b9d0a3849de012d3
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_getUncleByBlockHashAndIndex
        responses:
          '200':
            description: Returns the estimated priority fee per gas.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_block
        operationId: eth-getUncleByBlockHashAndIndex
