openapi: 3.1.0
info:
  title: net_version
  version: '1.0'
servers:
  - url: 'https://bsc-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: net_version
        description: Returns the current network id.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: 64a9df0874fb4a93b9d0a3849de012d3
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/net_version
        responses:
          '200':
            description: Returns the current network id.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/net_version
        operationId: net-version
