openapi: 3.1.0
info:
  title: debug_traceCall
  version: '1.0'
servers:
  - url: 'https://bsc-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      summary: debug_traceCall
      description: Runs an eth_call within the context of the given block execution using the final state of parent block as the base.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: 64a9df0874fb4a93b9d0a3849de012d3
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/debug_traceCall
      responses:
        '200':
          description: 'Returns - Array of block traces'
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/debug_traceCall
      operationId: debug-tracecall
