openapi: 3.1.0
info:
  title: debug_traceBlockByHash
  version: '1.0'
servers:
  - url: '{server_url}'
    variables:
      server_url:
        description: BSC Debug API url
        default: https://bsc-mainnet.nodereal.io/v1
tags:
paths:
  /{apiKey}:
    post:
      summary: debug_traceBlockByHash
      description: Replays the block that is already present in the database.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: 64a9df0874fb4a93b9d0a3849de012d3
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/debug_traceBlockByHash
      responses:
        '200':
          description: 'Returns - array of block traces'
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/debug_traceBlockByHash
      operationId: debug-traceblockbyhash
