openapi: 3.1.0
info:
  title: eth_getFilterLogs - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getFilterLogs.yaml#/components/pathItems/path/post
      operationId: eth-getfilterlogs-optimism
