openapi: 3.1.0
info:
  title: eth_getBlockByNumber - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getBlockByNumber.yaml#/components/pathItems/path/post
      operationId: eth-getblockbynumber-optimism
      x-readme:
        explorer-enabled: false
        samples-languages:
          - javascript
          - curl
          - python
          - go