openapi: 3.1.0
info:
  title: eth_getTransactionByHash - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getTransactionByHash.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionbyhash-optimism
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go
