openapi: 3.1.0
info:
  title: eth_getFilterChanges - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getFilterChanges.yaml#/components/pathItems/path/post
      operationId: eth-getfilterchanges-optimism
