openapi: 3.1.0
info:
  title: eth_getProof - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getProof.yaml#/components/pathItems/path/post
      operationId: eth-getproof-optimism
      x-readme:
        explorer-enabled: false
