openapi: 3.1.0
info:
  title: net_version - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/net_version.yaml#/components/pathItems/path/post
      operationId: net-version-optimism
