openapi: 3.0.0
info:
  title: Nebula Enhanced API
  description: Powered by MegaNode, NodeReal
  version: 0.0.1
components:
  schemas:
    TokenMeta:
      type: object
      properties:
        name:
          type: string
          example: USD Coin
        symbol:
          type: string
          example: USDC
        decimals:
          type: integer
          example: 18
    TokenMetaResponse:
      type: object
      properties:
        id:
          type: string
          example: 1
        jsonrpc:
          type: string
          example: '2.0'
        error:
          type: object
        result:
          type: object
          $ref: '#/components/schemas/TokenMeta'
servers:
  - url: 'https://bsc-mainnet.nodereal.io/v1'
paths:
  /{apiKey}/nr_getTokenMeta:
    post:
      summary: Get specific token's metadata.
      description: >-
        Return name, symbol and decimals of the token.

        - sugar: false

        - cost: 80
      tags:
        - Released
      parameters:
          - name: apiKey
            in: path
            schema:
              type: string
            required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                method:
                  type: string
                  example: nr_getTokenMeta
                jsonrpc:
                  type: string
                  example: '2.0'
                params:
                  type: array
                  description: >-
                    - token address: address of the token (ERC20/ERC721/ERC1155)

                  items:
                    type: string
                  example:
                    - '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenMetaResponse'
