openapi: 3.0.0
info:
  title: Nebula Enhanced API
  description: Powered by MegaNode, NodeReal
  version: 0.0.1
components:
  schemas:
    TokenMetabody:
      type: object
      properties:
        contract_address:
          type: string
          example: "0xEA5613EBBBE1E69BF5F05252C215462254F41565"
        toke_id:
          type: integer
          example: USDC
        toke_type:
          type: string
          default: ERC721
          enum:
            - ERC721
            - ERC1155
    TokenMetaResponse:
      type: object
      properties:
        contract_address:
          type: string
          example: "0xEA5613EBBBE1E69BF5F05252C215462254F41565"
        token_id:
          type: integer
          example: '2.0'
        meta_url:
          type: string
        meta:
          type: string
servers:
  - url: 'https://bsc-mainnet.nodereal.io/v1'
paths:
  /{apiKey}/nr_getTokenMeta:
    post:
      summary: Get specific NFT's metadata.
      description: >-
        This API method helps you to get the meta of an ERC1155/ERC721 token of an address.
      tags:
        - NFT
      parameters:
          - name: apiKey
            in: path
            schema:
              type: string
            required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                method:
                  type: string
                  example: nr_getTokenMeta
                jsonrpc:
                  type: string
                  example: '2.0'
                params:
                  type: string
                  description: >-
                    - token address: address of the token (ERC20/ERC721/ERC1155)

                  items:
                    type: string
                  example:
                    - '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d'
      responses:
        '200':
          description: This API method helps you to get the meta of an ERC1155/ERC721 token of an address.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenMetaResponse'
