openapi: 3.1.0
info:
  title: bor_getAuthor - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      summary: bor_getAuthor
      description: 'Polygon API - Returns address of Author.'
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: f510fc4d083b49d1ab383d25246cc7de
          required: true
      requestBody:
        description: 'Block number (in hexadecimal format).'
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/bor_getAuthor
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/bor_getAuthor
      operationId: bor-getauthor-polygon
