openapi: 3.1.0
info:
  title: eth_getUncleByBlockNumberAndIndex
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getUncleByBlockNumberAndIndex
        description: Returns information about an uncle of a block by number and uncle index position.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: 1659dfb40aa24bbb8153a677b98064d7
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_getUncleByBlockNumberAndIndex
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_block
        operationId: eth-getUncleByBlockNumberAndIndex
