openapi: 3.1.0
info:
  title: eth_sendRawTransaction
  version: '1.0'
servers:
  - url: 'https://ethw-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_sendRawTransaction
        description: Creates a new message call transaction or a contract creation for signed transactions.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f8728a3265504b998a2f09c83493d76a
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_sendRawTransaction
        responses:
          '200':
            description: 'Returns 32 Bytes - the transaction hash, or the zero hash if the transaction is not yet available.'
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/string_result_response
        operationId: eth-sendRawTransaction
