openapi: 3.1.0
info:
  title: eth_getUncleCountByBlockNumber
  version: '1.0'
servers:
  - url: 'https://ethw-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getUncleCountByBlockNumber
        description: Returns the number of uncles in a block matching the give block number.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f8728a3265504b998a2f09c83493d76a
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_getUncleCountByBlockNumber
        responses:
          '200':
            description: Returns integer of the number of uncles in this block.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/string_result_response
        operationId: eth-getUncleCountByBlockNumber
