openapi: 3.1.0
info:
  title: eth call
  description: Executes a new message call immediately without creating a transaction on the block chain.
  version: '1.0'
servers:
  - url: 'https://ethw-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: eth-call
        summary: eth_call
        description: Executes a new message call immediately without creating a transaction on the block chain.
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f8728a3265504b998a2f09c83493d76a
            required: true
        requestBody:
          description: Accepts the transaction call object.
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_call_550_gas
        x-readme:
          explorer-enabled: false
          samples-languages:
            - javascript
            - curl
            - python
            - go
        responses:
          '200':
            description: Returns integer of the number of transactions in this block.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/string_result_response
