openapi: 3.1.0
info:
  title: eth_chainId
  version: '1.0'
servers:
  - url: 'https://ethw-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_chainId
        description: 'The chain ID returned should always correspond to the information in the current known head block. This ensures that caller of this RPC method can always use the retrieved information to sign transactions built on top of the head.'
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f8728a3265504b998a2f09c83493d76a
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_chainId
        responses:
          '200':
            description: Returns integer of the current chain ID.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/string_result_response
        operationId: eth-chainId
