openapi: 3.1.0
info:
  title: eth_gasPrice
  version: '1.0'
servers:
  - url: 'https://ethw-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_gasPrice
        description: Returns the current price per gas in wei.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f8728a3265504b998a2f09c83493d76a
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_gasPrice
        x-readme:
          explorer-enabled: false
          samples-languages:
            - javascript
            - curl
            - python
            - go
        responses:
          '200':
            description: Returns integer of the current gas price in wei.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/string_result_response
        operationId: eth-gasPrice
