openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByNumber - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getBlockTransactionCountByNumber.yaml#/components/pathItems/path/post
      operationId: eth-getblocktransactioncountbynumber-polygon
      parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f510fc4d083b49d1ab383d25246cc7de
            required: true
