openapi: 3.1.0
info:
  title: eth_getStorageAt - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getStorageAt.yaml#/components/pathItems/path/post
      operationId: eth-getstorageat-polygon
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: f510fc4d083b49d1ab383d25246cc7de
          required: true
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go