openapi: 3.1.0
info:
  title: eth_getSignersAtHash - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      summary: eth_getSignersAtHash
      description: 'Polygon API - Returns all signs given a blockhash.'
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: f510fc4d083b49d1ab383d25246cc7de
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getSignersAtHash
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/eth_getSignersAtHash
      operationId: eth-getsignersathash-polygon
