openapi: 3.1.0
info:
  title: eth_newPendingTransactionFilter - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_newPendingTransactionFilter.yaml#/components/pathItems/path/post
      operationId: eth-newpendingtransactionfilter-polygon
