openapi: 3.1.0
info:
  title: eth_getTransactionReceipt - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getTransactionReceipt.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionreceipt-polygon
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go