openapi: 3.1.0
info:
  title: eth_getRootHash - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      summary: eth_getRootHash
      description: 'Polygon API - Returns the root hash given a block range.'
      tags: []
      parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f510fc4d083b49d1ab383d25246cc7de
            required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getRootHash
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/bor_getRootHash
      operationId: eth-getroothash-polygon
