openapi: 3.1.0
info:
  title: eth_newBlockFilter - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_newBlockFilter.yaml#/components/pathItems/path/post
      operationId: eth-newblockfilter-polygon
