openapi: 3.1.0
info:
  title: eth_getCode - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.nodereal.io/v1'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getCode.yaml#/components/pathItems/path/post
      operationId: eth-getcode-polygon
      parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: f510fc4d083b49d1ab383d25246cc7de
            required: true
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go