# For info on getting the latest rdme version and obtaining your API_DEFINITION_ID,
# see our docs: https://docs.readme.com/docs/rdme#example-syncing-an-openapi-definition
name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@7.3.0
        with:
          rdme: openapi ./portal --key=rdme_xn8s9h79c3dabaff0d638d4c2dcd378b34b5659b27ec9c09e79889f52741beea66660e --id=API_DEFINITION_ID
